### 36310035 is venueId user1 is userId
PUT http://localhost:8080/addVenue/36310035/toFavourite HTTP/1.1
Authorization: user1

###
GET http://localhost:8080/profile
Authorization: user1

###
PUT http://localhost:8080/delVenue/36310035/fromFavourite HTTP/1.1
Authorization: user1

###






### must have userId (role=admin) and venueId
POST http://localhost:8080/addEventToVenue/36310035 HTTP/1.1
Content-Type: application/json
Authorization: user1

{
    "titlee": "testing 1"
}

### 1702304074087 is eventId
DELETE http://localhost:8080/deleteEvent/1702398228329/fromVenue/36310035
Authorization: user1

### put any thing want to be updated into the body except _id and eventId, but i wont check
PUT http://localhost:8080/updateEvent/1702398228329
Content-Type: application/json
Authorization: user1

{
    "pricee": "0",
    "presenterorge": "coslin tsang"
}






###
GET http://localhost:8080/getAllVenue
Authorization: user1

###
POST http://localhost:8080/genCodeForRegister
Content-Type: application/json

{
    "email": "romog15854@anawalls.com"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "qq",
    "email": "romog15854@anawalls.com",
    "password": "123",
    "role": "user",
    "code": "515925"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "q",
    "password": "321"
}

###
POST http://localhost:8080/genCodeForForgetPassword
Content-Type: application/json

{
    "userId": "q",
    "email": "romog15854@anawalls.com"
}

###
POST http://localhost:8080/forgetPassword
Content-Type: application/json

{
    "userId": "q",
    "email": "romog15854@anawalls.com",
    "code": "tFPl_hCLVo",
    "password": "321"
}

###
POST http://localhost:8080/resetPassword
Content-Type: application/json
Authorization: user3

{
    "password": "1234",
    "newpassword":"1234"
}

###
DELETE http://localhost:8080/delUser/user3
Authorization: user1

###
GET http://localhost:8080/getAllUser
Authorization: user1

###
PUT http://localhost:8080/updateUser/user3
Content-Type: application/json
Authorization: user1

{
    "userId":"user3",
    "password": "321"
}

###








###
POST http://localhost:8080/addComment HTTP/1.1
Content-Type: application/json
Authorization: user1

{
    "venueId": "36310035",
    "comment": "testing 1"
}

###
DELETE http://localhost:8080/delComment/65788a216b792aa2436ae6e6 HTTP/1.1
Authorization: user1

###
GET http://localhost:8080/getAllCommentFor/36310035
Authorization: user1
